### ISSUE TITLE
Safeguard for Stochastic programs with Integer recourses

### ISSUE THREAD

**Issue by TheoGuyard** [martinbiel/StochasticPrograms.jl#24]
Hey ! There is no safeguard for model with integer recourses. The standard L-Shaped method (for instance) can not be used in such cases. A safeguard could prevent errors of type `ERROR: Gurobi Error 10005: Unable to retrieve attribute 'Pi'` when adding new cuts during the method.

**Comment by martinbiel** [comment]
There are now two experimental extensions that handle integer recourse in the L-shaped algorithm, on the master branch. They are activated by either 
```
set_optimizer_attribute(sp, IntegerStrategy(), CombinatorialCuts())
```
 or 
```
set_optimizer_attribute(sp, IntegerStrategy(), Convexification())
```
The default `IntegerStrategy`, `IgnoreIntegers`, includes the safeguard checks suggested here. Thanks!
