### ISSUE TITLE
Comptability with JuMP (UndefVarError: @stochastic_model)

### ISSUE THREAD

**Issue by bandayachul** [martinbiel/StochasticPrograms.jl#3]
This package looks quite good. As discussed on [discourse ](https://discourse.julialang.org/t/stochastic-programming-undefvarerror/34608/4), the StochasticPrograms package does not appear to be updated to the latest version of JuMP. 

Running the [farmer example](https://martinbiel.github.io/StochasticPrograms.jl/stable/manual/examples/) given in the documentation gives “UndefVarError: @stochastic_model not defined” error.

Is the package/documentation going to be updated?

**Comment by Thuener** [comment]
Any news on that?

**Comment by martinbiel** [comment]
Hey,

I have a local development branch with a redesign that is compatible with the latest version of JuMP+MathOptInterface. It is close to functional but not yet finished, and I cannot now say for sure when it will be (on work leave atm). Until then, the best approach is to rely on environments to ensure that StochasticPrograms is used with the older version of JuMP. I think the “UndefVarError: @stochastic_model not defined” error stems from also having the latest JuMP master installed which seems to confuse the package manager.

**Comment by martinbiel** [comment]
The latest version now support the new JuMP+MathOptInterface. Closing this.
