### ISSUE TITLE
Shadow price of named constraint

### ISSUE THREAD

**Issue by simontherien** [martinbiel/StochasticPrograms.jl#38]
Hello, I am trying to retrieve the shadow price for a first stage constraint `@constraint(slpr_bp, cap, x_1 + x_2 <= 4 - η_hat)` as such but I get the error _UndefVarError: cap not defined_ when calling `shadow_price(cap, 1)` JuMP method (1 for first stage). Is this expected? How do I explicitly reference a named constraint of a certain stage? Thanks!

**Comment by martinbiel** [comment]
You need to acquire a `SPConstraintRef` of the desired constraint first. The easiest for a named constraint is through `cap = sp[1,:cap]`, where `sp` is your stochastic program instance and `1` is the stage. Relevant docs are [here](https://martinbiel.github.io/StochasticPrograms.jl/stable/manual/decisions/).
