### ISSUE TITLE
Update to latest version of JuMP and MOI

### ISSUE THREAD

**Issue by odow** [martinbiel/StochasticPrograms.jl#40]
This is causing people problems: https://github.com/martinbiel/StochasticPrograms.jl/blob/cb38c4ca70366b770017c7225324bc19a4080c2a/Project.toml#L30

x-ref: https://github.com/jump-dev/Gurobi.jl/issues/445

**Comment by davide-f** [comment]
I'm experiencing the same problem; recommend JuMP version 0.22 and mathoptinterface 0.10 and MutableArithmetics 0.2

Probably it is not worthy to specify also the third layer like 0.2.22, unless the specific version is required

**Comment by martinbiel** [comment]
The breaking changes in 0.10 will require a few redesigns, so unfortunately I cannot just bump the versions.
