### ISSUE TITLE
Downgrades the Gurobi version 

### ISSUE THREAD

**Issue by akulbansal5** [martinbiel/StochasticPrograms.jl#46]
Installing the package StochasticPrograms.jl downgrades Gurobi v0.11.5 to Gurobi v0.11.3. This results in "Failed to precompile Gurobi" error while importing the Gurobi package. I am using Gurobi version 9.1.2 on my mac.

**Comment by odow** [comment]
See https://github.com/martinbiel/StochasticPrograms.jl/issues/49

**Comment by odow** [comment]
Closing as duplicate of #49
