### ISSUE TITLE
Normalized coefficient of "decision" variables

### ISSUE THREAD

**Issue by rtwalker** [martinbiel/StochasticPrograms.jl#9]
I'm running into errors using the `normalized_coefficient` function on variables that are of type `DecisionRef` or `KnownRef`.
If the decision variable isn't in the constraint, I'd prefer it to return 0 rather than throwing an error. 

Of course I can do some filtering on the front end to avoid calling `normalized_coefficient` for constraints that aren't `AffineDecisonFunction`s, but for the sake of convenience/completeness, I wanted to check whether you would be open to a PR adding the following methods?

```julia
function JuMP._affine_coefficient(f::_VariableAffExpr{C}, decision::DecisionRef) where C
    return zero(C)
end
```

```julia
function JuMP._affine_coefficient(f::_VariableAffExpr{C}, known::KnownRef) where C
    return zero(C)
end

```

**Comment by martinbiel** [comment]
Fine by me! Looking at the JuMP definitions this should probably be the intended behavior anyway.

**Comment by rtwalker** [comment]
Great! I'll turn it into a PR a little later today
